# Idea is to shorten and ease the process of generating a Tripwire recon note from D-Scan results in EVE Online.
# Usage: Copy D-Scan results to clipboard, run this script, and it will generate a formatted recon note.
# Paste to tripwire - job done.
# Note - Beta Script - to be expanded/set to production 2025 - @ScottishDex/Dexomus Viliana - @MacGuinessWDS/Ryan Ruby
# Do not use in production without testing and validation (And CCP will find out and slice off things)

Add-Type -AssemblyName PresentationCore # Core module - (discovered through jabbing at AI)

#Target ship list from Json file

$shipJson = Get-Content -Path "eve_ships.json" -Raw | ConvertFrom-Json
$shipList = $shipJson.ships

#Get clipboard content
$clipboard = [Windows.Clipboard]::GetText()
if (-not $clipboard) {
    Write-Error "❌ Clipboard is empty."
    exit 1
}
# Integrated error handling for empty clipboard

$lines = $clipboard -split "`r?`n"  # Split clipboard content into lines to read each D-Scan result

# Filtering lines that match any of the target patterns - used for testing against D-Scan results.
$matchedLines = @()
foreach ($line in $lines) {
    foreach ($pattern in $targetPatterns) {
        if ($line -like "*$shipList*") {
            $matchedLines += $line
            break
        }
    }
}

# System name extraction - regex only for wormhole systems
$system = ($lines -join "`n") -match '(^J\d{6}$)\s+'; if ($matches) { $matches[1] } else { "Non-Wormhole System" }

# Timestamp
$timestamp = (Get-Date).ToUniversalTime().ToString("yyyy-MM-dd HH:mm") + " UTC"

# To do list - customize to suit wormhole navigation and trim nonsense (again, generated by chat gpt due to lazyness)
$note = if ($matchedLines.Count -gt 0) {
@"
**🛰️ Tripwire Recon – $system**
📍 Status: Contacts detected.

📡 D-Scan Intel:
$($matchedLines -join "`n")

🕓 Time: $timestamp
🧭 Scout: [YourNameHere]
"@
} else {
@"
**🛰️ Tripwire Recon – $system**
📍 Status: No targets of interest detected.

📡 D-Scan checked for:
$($targetPatterns -join ", ")

🕓 Time: $timestamp
🧭 Scout: [YourNameHere]
"@
}

# Fires the note to clipboard and saves it to a file with a timestamp - paste to Tripwire or any other tool you use for recon notes.
# Additional options are web hook? Double I can get access?

$note | Set-Clipboard
$note | Out-File -FilePath "TripwireRecon_$($system)_$(Get-Date -Format 'yyyyMMdd_HHmm').txt"
Write-Host "`n✅ Recon note generated and copied to clipboard."